### ISSUE TITLE
Exponential stepping and impact on synthetic scenes. Poor synthetic scene results. 

### ISSUE THREAD

**Issue by maturk** [kwea123/ngp_pl#106]
Hi @kwea123,

I have had some difficulties training on a custom synthetic dataset and I am looking to improve the rendering results. I noticed a dramatic difference when setting exp_step_factor=0. I also saw that in the code, exp_step_factor controls the color of the background in __render_rays_train and also 'min_sample' in __render_rays_test. 

Could you give some tips on training with synthetic data? 

Could you also provide some intuition or clarification on the effects of exponential stepping, rgb_bg (why do you set it to (1,1,1) for synthetic scenes), and min_sample (why min_sample == 1 for synthetic scenes) when training with small synthetic scenes? 

Thanks a lot for your time and effort with this project, it has helped me a lot. 

Best,
maturk

**Comment by kwea123** [comment]
For `exp_step_factor`, please see the paper (they call it `cone_angle`), basically it's increasing step size when the sample is far away from the camera to capture very long distance objects. In synthetic scene we only focus on the near object, so setting it to 0 is better.

`rgb_bg` is 1 because the dataset has white background (actually it's transparent but we define it as white, ofc you can change this to whatever color you want, just make sure you have defined the same color in `synthetic_nsvf.py` too.)
`min_sample` is 1 just like what I commented, since most of the image is background, 1 sample is enough to skip everything in the background (and render that pixel as white), so it's more efficient.
