### ISSUE TITLE
Question about update_density_grid function ?

### ISSUE THREAD

**Issue by phongnhhn92** [kwea123/ngp_pl#4]
Hi, thanks for the code !

I have one question about this update_density_grid [function](https://github.com/kwea123/ngp_pl/blob/da4b65493f72f27744f28f630497be55b3965545/models/networks.py#L149). Can u explain why we need to do this update with density_grid and density_bitfield ?

**Comment by kwea123** [comment]
This is a trick used in the paper to accelerate ray marching (section E.2). Basically we keep track of a rough occupancy field to skip empty space in ray marching.

Another small implementation difference is that I set the density threshold as `0.05*...` instead of `0.01*...` in the paper because I found `0.05` leads to faster convergence, but actually this number might not be that important.
