### ISSUE TITLE
CUDA OOM error when validating

### ISSUE THREAD

**Issue by QinlongHuang** [kwea123/ngp_pl#44]
Hi kwea123, thanks for your great work on NGP.
I have tried mipnerf360 datasets and the gpu I used is NVIDIA V100 16G.
On training phase, the gpu memory used is ~6G, but when on validatation phase, I will get an OOM error. The batchsize I tried includes 4096 and 8192.

**Comment by QinlongHuang** [comment]
@kwea123 thx for your quick reply !
The command is `python train.py --root_dir ./data/mipnerf360/garden/ --exp_name garden  --dataset_name colmap --no_save_test`.
I just wonder why so much memory used on validation phase. Because it just used ~6G when training.

**Comment by kwea123** [comment]
Because in training it's only 8k rays per batch, but in validation it renders **all rays** at once (there is no `chunk` argument like in the original nerf at the moment). If you want to render high resolution image, you need to do chunking like original nerf. I will try to add this too, it should be easy.
