### ISSUE TITLE
Samples Per Ray

### ISSUE THREAD

**Issue by lukasHoel** [kwea123/ngp_pl#46]
Hi,

thank you for providing this amazing codebase!
I wonder if you have an intuition about the samples/ray in your implementation vs instant-ngp?
Yours drops to around ~25, while theirs drops to around ~6 on the lego scene after 5K steps.

Are you actually taking smaller steps along a ray or sth?

Thank you!

**Comment by kwea123** [comment]
Actually this number is the number of samples allocated for `RayMarcher`, which is an upper bound of the samples required for `VolumeRenderer`. RayMarcher allocates samples for occupied space, while VolumeRenderer stops marching if the transmittance is below a threshold (1e-4).
For training, I didn't implement functionality to count the samples in VolumeRenderer since it is just for counting, but I implemented counting in RayMarcher since it serves to remove redundant samples.https://github.com/kwea123/ngp_pl/blob/d4d1b71d6b18b3c0da68032c706fba344352263e/models/custom_functions.py#L92-L97
However for testing, I did keep track of all effective samples:
https://github.com/kwea123/ngp_pl/blob/d4d1b71d6b18b3c0da68032c706fba344352263e/models/rendering.py#L87
I believe the samples/ray in instant-ngp is the number of effective samples (i.e. in VolumeRenderer), and I've checked that in testing my number matches that of instant-ngp (i.e. around 6 as you said)

I'll find time to implement counting effective number of samples in training too

**Comment by kwea123** [comment]
This functionality is added, now I log `rm_s` (ray marching samples) and `vr_s` (volume rendering samples) at the same time. `vr_s` reaches 5~6 very quickly as shown:
<img width="1381" alt="スクリーンショット 2022-08-26 10 04 51" src="https://user-images.githubusercontent.com/11364490/186801060-74706284-9e26-4b52-81d3-c81fe3927990.png">

**Comment by lukasHoel** [comment]
Thank you for your help, really appreciate it :)
