### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Yukun66** [kwea123/ngp_pl#69]
Hi! Thanks for this great work! My question is:  It will output a 'Segmentation fault' after the whole process of training. And the test images are output correctly if I don't change the 'scale'. Thanks~

**Comment by kwea123** [comment]
It is possibly due to OOM (RAM), you might need to disable validation by setting this number to `0`
https://github.com/kwea123/ngp_pl/blob/6b2a66928d032967551ab98d5cd84c7ef1b83c3d/train.py#L265
and do validation elsewhere (eg. in the notebook)

**Comment by Yukun66** [comment]
> It is possibly due to OOM (RAM), you might need to disable validation by setting this number to `0`
> 
> https://github.com/kwea123/ngp_pl/blob/6b2a66928d032967551ab98d5cd84c7ef1b83c3d/train.py#L265
> 
> 
> and do validation elsewhere (eg. in the notebook)

I monitored my memory states, and find out that my swap space is filled out and didn't get emptied. Could this bug be the reason?

**Comment by kwea123** [comment]
My bad, not this argument, you need to manually comment out 
https://github.com/kwea123/ngp_pl/blob/6b2a66928d032967551ab98d5cd84c7ef1b83c3d/train.py#L148-L152
to disable validation.

> my swap space is filled out

Yes, it's due to insufficient memory, either you have too small memory, or you are loading too large images (especially those from iPhone with 4032x3024 resolution, you need `--downscale 0.25` to scale them down)
